version: '3'

networks:
  standup_fails_app:
    external: true

services:
  postgres:
    container_name: standup_fails_db
    image: postgres:9.6.0
    volumes:
      - standup-fails-api-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "standupfails"
    networks:
      - standup_fails_app

  standupfailsapi:
    container_name: standup_fails_api
    image: standupfailsapi:latest
    ports:
      - "8880:8880"
    environment:
      DB_URL: "
      DB_USER: ""
      DB_PASSWORD: ""
      SECRET_KEY: 123
      JWT_SECRET: 123
    networks:
      - standup_fails_app
    depends_on:
      - postgres

volumes:
  standup-fails-api-data:
