version: '3'

networks:
  standup_fails_app:
    external: true

services:
  postgres:
    container_name: standup_fails_db
    image: postgres:9.6.0
    restart: always
    volumes:
      - standup-fails-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    env_file:
      - .env
    networks:
      - standup_fails_app

  standupfailsapi:
    container_name: standup_fails_api
    image: standupfailsapi:latest
    ports:
      - "8880:8880"
    env_file:
      - .env
    networks:
      - standup_fails_app
    depends_on:
      - postgres

volumes:
  standup-fails-data:
